In [2]:
#importa pandas e numpy

import pandas as pd
import numpy as np

In [3]:
#leggi con il csv il file ./heart_disesases.csv

df = pd.read_csv('./heart_disease.csv')

#stampa le prime 5 righe del dataset

df.head(5)

,Age,Gender,Blood_Pressure,Cholesterol_Level,Exercise_Habits,Smoking,Family_Heart_Disease,Diabetes,BMI,High_Blood_Pressure,...,High_LDL_Cholesterol,Alcohol_Consumption,Stress_Level,Sleep_Hours,Sugar_Consumption,Triglyceride_Level,Fasting_Blood_Sugar,CRP_Level,Homocysteine_Level,Heart_Disease_Status
0,56.0,Male,153.0,155.0,High,Yes,Yes,No,24.991591,Yes,...,No,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No
1,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,No,...,No,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No
2,46.0,Male,126.0,216.0,Low,No,No,No,29.855447,No,...,Yes,Low,Low,4.440440,Low,393.0,92.0,12.709873,11.230926,No
3,32.0,Female,122.0,293.0,High,Yes,Yes,No,24.130477,Yes,...,Yes,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No
4,60.0,Male,166.0,242.0,Low,Yes,Yes,Yes,20.486289,Yes,...,No,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No

In [6]:
#stampa i dati relativi ai fumatori

df[df['Smoking'] == "Yes"]

,Age,Gender,Blood_Pressure,Cholesterol_Level,Exercise_Habits,Smoking,Family_Heart_Disease,Diabetes,BMI,High_Blood_Pressure,...,High_LDL_Cholesterol,Alcohol_Consumption,Stress_Level,Sleep_Hours,Sugar_Consumption,Triglyceride_Level,Fasting_Blood_Sugar,CRP_Level,Homocysteine_Level,Heart_Disease_Status
0,56.0,Male,153.0,155.0,High,Yes,Yes,No,24.991591,Yes,...,No,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No
3,32.0,Female,122.0,293.0,High,Yes,Yes,No,24.130477,Yes,...,Yes,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No
4,60.0,Male,166.0,242.0,Low,Yes,Yes,Yes,20.486289,Yes,...,No,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No
5,25.0,Male,152.0,257.0,Low,Yes,No,No,28.144681,No,...,No,Low,Medium,5.504876,Low,126.0,91.0,4.297575,10.815983,No
6,78.0,Female,121.0,175.0,High,Yes,Yes,Yes,18.042332,No,...,No,Medium,Medium,9.240911,Medium,107.0,85.0,11.582983,19.659461,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,73.0,Female,144.0,191.0,Medium,Yes,Yes,Yes,39.459620,No,...,No,Medium,Low,7.549114,Medium,200.0,88.0,1.154904,8.021732,Yes
9995,25.0,Female,136.0,243.0,Medium,Yes,No,No,18.788791,Yes,...,Yes,Medium,High,6.834954,Medium,343.0,133.0,3.588814,19.132004,Yes
9997,73.0,Male,152.0,201.0,High,Yes,No,Yes,26.899911,No,...,Yes,NaN,Low,4.436762,Low,248.0,88.0,4.408867,9.492429,Yes
9998,23.0,Male,142.0,299.0,Low,Yes,No,Yes,34.964026,Yes,...,Yes,Medium,High,8.526329,Medium,113.0,153.0,7.215634,11.873486,Yes
9999,38.0,Female,128.0,193.0,Medium,Yes,Yes,Yes,25.111295,No,...,Yes,High,Medium,5.659394,High,121.0,149.0,14.387810,6.208531,Yes

In [8]:
# i dati relativi all'etÃ  e pressione delle donne che soffrono di diabete fai riferimento ai dati caricati

df[(df['Gender'] == 'Female') & (df['Diabetes'] == 'Yes')]

,Age,Gender,Blood_Pressure,Cholesterol_Level,Exercise_Habits,Smoking,Family_Heart_Disease,Diabetes,BMI,High_Blood_Pressure,...,High_LDL_Cholesterol,Alcohol_Consumption,Stress_Level,Sleep_Hours,Sugar_Consumption,Triglyceride_Level,Fasting_Blood_Sugar,CRP_Level,Homocysteine_Level,Heart_Disease_Status
1,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,No,...,No,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No
6,78.0,Female,121.0,175.0,High,Yes,Yes,Yes,18.042332,No,...,No,Medium,Medium,9.240911,Medium,107.0,85.0,11.582983,19.659461,No
7,38.0,Female,161.0,187.0,Low,Yes,Yes,Yes,34.736683,No,...,No,Low,Medium,7.841008,High,228.0,111.0,4.929381,17.146599,No
8,56.0,Female,135.0,291.0,Low,No,Yes,Yes,34.493112,Yes,...,Yes,High,Low,6.941403,High,317.0,103.0,5.119015,6.051129,No
11,40.0,Female,134.0,296.0,High,No,Yes,Yes,31.739622,No,...,No,NaN,Medium,6.765162,Medium,109.0,139.0,6.694785,19.440650,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9990,55.0,Female,131.0,160.0,High,Yes,No,Yes,32.363462,No,...,No,Low,Medium,5.018783,Medium,267.0,129.0,0.603213,11.298252,Yes
9991,41.0,Female,160.0,241.0,Medium,No,Yes,Yes,39.346342,Yes,...,Yes,NaN,High,4.343666,Low,178.0,106.0,4.718864,14.219791,Yes
9993,27.0,Female,153.0,188.0,Medium,No,No,Yes,28.173059,Yes,...,No,NaN,Medium,4.834842,High,300.0,118.0,6.216700,13.114808,Yes
9994,73.0,Female,144.0,191.0,Medium,Yes,Yes,Yes,39.459620,No,...,No,Medium,Low,7.549114,Medium,200.0,88.0,1.154904,8.021732,Yes
9999,38.0,Female,128.0,193.0,Medium,Yes,Yes,Yes,25.111295,No,...,Yes,High,Medium,5.659394,High,121.0,149.0,14.387810,6.208531,Yes

In [10]:
#numero totale di fumatori maschi

df[df['Gender'] == 'Male']['Smoking'].value_counts()

Smoking
Yes    2538
No     2455
Name: count, dtype: int64